build_client:
	docker build -t eea-client -f client/Dockerfile client/.

build_server:
	docker build -t eea-server -f server/Dockerfile server/.

build_tee:
	docker build -t tee -f tee/Dockerfile tee/.